[package]
name = "vortex-proto"
authors = { workspace = true }
categories = { workspace = true }
description = "Protocol buffer definitions for Vortex types"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }

[features]
dtype = []
expr = ["dtype", "scalar"]
scalar = ["dtype"]

default = ["expr"]

[lints]
workspace = true
