[package]
name = "vortex-fastlanes"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex fastlanes arrays"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
arrayref = { workspace = true }
arrow-buffer = { workspace = true }
fastlanes = { workspace = true }
itertools = { workspace = true }
lending-iterator = { workspace = true }
num-traits = { workspace = true }
prost = { workspace = true }
rand = { workspace = true, optional = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-mask = { workspace = true }
vortex-scalar = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
vortex-alp = { path = "../alp" }
vortex-array = { workspace = true, features = ["test-harness"] }
vortex-fastlanes = { path = ".", features = ["test-harness"] }

[features]
test-harness = ["dep:rand"]

[[bench]]
name = "bitpacking_take"
harness = false

[[bench]]
name = "bitpacking_decompress_selection"
harness = false

[[bench]]
name = "canonicalize_bench"
harness = false
required-features = ["test-harness"]

[[bench]]
name = "compute_between"
harness = false
required-features = ["test-harness"]
