[package]
name = "vortex-dtype"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex's core type system"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
arbitrary = { workspace = true, optional = true }
arrow-schema = { workspace = true, optional = true }
flatbuffers = { workspace = true }
half = { workspace = true, features = ["num-traits"] }
itertools = { workspace = true }
jiff = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
rkyv = { workspace = true, optional = true, features = ["bytecheck"] }
serde = { workspace = true, optional = true, features = ["rc", "derive"] }
static_assertions = { workspace = true }
vortex-error = { workspace = true, features = ["flatbuffers"] }
vortex-flatbuffers = { workspace = true, features = ["dtype"] }
vortex-proto = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
serde_test = { workspace = true }

[lints]
workspace = true

[features]
default = ["arrow"]
arrow = ["dep:arrow-schema"]
proto = ["vortex-proto/dtype"]
serde = ["dep:serde"]
