[package]
name = "vortex-duckdb"
version = { workspace = true }
description = "Vortex's duckdb adapter"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = false
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
categories = { workspace = true }
readme = { workspace = true }

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
bench = false
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
itertools = { workspace = true }
num-traits = { workspace = true }
vortex = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
duckdb = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
