[workspace]
members = [
    "bench-vortex",
    "encodings/*",
    "fuzz",
    "pyvortex",
    "vortex",
    "vortex-array",
    "vortex-buffer",
    "vortex-datafusion",
    "vortex-datetime-dtype",
    "vortex-dtype",
    "vortex-error",
    "vortex-expr",
    "vortex-file",
    "vortex-flatbuffers",
    "vortex-io",
    "vortex-ipc",
    "vortex-layout",
    "vortex-mask",
    "vortex-proto",
    "vortex-sampling-compressor",
    "vortex-scalar",
    "vortex-scan",
    "vortex-tui",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.24.0"
homepage = "https://github.com/spiraldb/vortex"
repository = "https://github.com/spiraldb/vortex"
authors = ["Vortex Authors <hello@vortex.dev>"]
license = "Apache-2.0"
keywords = ["vortex"]
include = [
    "benches/*.rs",
    "build.rs",
    "src/**/*.rs",
    "Cargo.toml",
    "proto/**/*.proto",
    "flatbuffers/**/*.fbs",
    "README.md",
]
edition = "2021"
rust-version = "1.82"
readme = "README.md"
categories = ["database-implementations", "data-structures", "compression"]

[workspace.dependencies]
anyhow = "1.0.95"
arbitrary = "1.3.2"
arrayref = "0.3.7"
arrow = "53.3"
arrow-arith = "53.3"
arrow-array = "53.3"
arrow-buffer = "53.3"
arrow-cast = "53.3"
arrow-ord = "53.3"
arrow-schema = "53.3"
arrow-select = "53.3"
arrow-string = "53.3"
async-once-cell = "0.5.4"
async-trait = "0.1.86"
pkg-config = "0.3.31"
backtrace = "0.3.74"
bytes = "1.9"
bzip2 = "0.5.0"
cfg-if = "1"
chrono = "0.4.38"
clap = "4"
compio = { version = "0.13", features = ["io-uring"], default-features = false }
criterion = { package = "codspeed-criterion-compat", features = [
    "html_reports",
], version = "2.7.2" }
croaring = "2.1.0"
crossterm = "0.28"
datafusion = { version = "44.0.0", default-features = false }
datafusion-common = "44"
datafusion-execution = "44"
datafusion-expr = "44"
datafusion-physical-expr = "44"
datafusion-physical-plan = "44"
divan = "0.1.14"
dyn-hash = "0.2.0"
enum-iterator = "2.0.0"
fastlanes = "0.1.5"
flatbuffers = "25"
flexbuffers = "25"
flume = "0.11"
fsst-rs = "0.5.0"
futures = { version = "0.3.31", default-features = false }
futures-executor = "0.3.31"
futures-util = "0.3.31"
getrandom = "0.2.14"
goldenfile = "1"
half = { version = "2.2.1", features = ["std", "num-traits"] }
hashbrown = "0.15.1"
homedir = "0.3.3"
humansize = "2.1.3"
indicatif = "0.17.8"
itertools = "0.14.0"
jiff = "0.1.29"
libfuzzer-sys = "0.4"
log = "0.4.21"
mimalloc = "0.1.42"
moka = { version = "0.12.10", default-features = false }
governor = "0.8"
num-traits = "0.2.19"
num_enum = "0.7.2"
object_store = "0.11.0"
oneshot = "0.1.10"
parquet = "53.3"
paste = "1.0.15"
pin-project = "1.1.5"
pin-project-lite = "0.2.15"
prost = "0.13.4"
prost-build = "0.13.4"
prost-types = "0.13.4"
pyo3 = { version = ">= 0.22", features = ["extension-module", "abi3-py310"] }
pyo3-log = ">= 0.11"
rancor = "0.1.0"
rand = "0.8.5"
rand_distr = "0.4"
ratatui = "0.29"
rayon = "1.10.0"
regex = "1.11.0"
reqwest = { version = "0.12.0", features = [
    "charset",
    "http2",
    "macos-system-configuration",
    "blocking",
    "rustls-tls",
], default-features = false }
# TODO(ngates): remove the unaligned rkyv feature when we move to 8-byte metadata.
rkyv = { version = "0.8.10", features = [
    "little_endian",
    "pointer_width_32",
    "bytecheck",
    "unaligned",
] }
rstest = "0.24"
rustc-hash = "2"
serde = "1.0.203"
serde_json = "1.0.116"
serde_test = "1.0.176"
simplelog = { version = "0.12.2", features = ["paris"] }
static_assertions = "1.1"
tabled = { version = "0.18.0", default-features = false }
tar = "0.4"
tempfile = "3"
tikv-jemallocator = "0.6"
thiserror = "2.0.3"
tokio = "1.36"
tracing = "0.1.37"
url = "2.4"
uuid = "1.8.0"
wasm-bindgen-futures = "0.4.39"

# BEGIN crates published by this project
vortex = { version = "0.24.0", path = "./vortex" }
vortex-alp = { version = "0.24.0", path = "./encodings/alp" }
vortex-array = { version = "0.24.0", path = "./vortex-array" }
vortex-buffer = { version = "0.24.0", path = "./vortex-buffer" }
vortex-bytebool = { version = "0.24.0", path = "./encodings/bytebool" }
vortex-datafusion = { version = "0.24.0", path = "./vortex-datafusion" }
vortex-datetime-dtype = { version = "0.24.0", path = "./vortex-datetime-dtype" }
vortex-datetime-parts = { version = "0.24.0", path = "./encodings/datetime-parts" }
vortex-dict = { version = "0.24.0", path = "./encodings/dict" }
vortex-dtype = { version = "0.24.0", path = "./vortex-dtype", default-features = false }
vortex-error = { version = "0.24.0", path = "./vortex-error" }
vortex-expr = { version = "0.24.0", path = "./vortex-expr" }
vortex-fastlanes = { version = "0.24.0", path = "./encodings/fastlanes" }
vortex-file = { version = "0.24.0", path = "./vortex-file", default-features = false }
vortex-flatbuffers = { version = "0.24.0", path = "./vortex-flatbuffers" }
vortex-fsst = { version = "0.24.0", path = "./encodings/fsst" }
vortex-io = { version = "0.24.0", path = "./vortex-io" }
vortex-ipc = { version = "0.24.0", path = "./vortex-ipc" }
vortex-layout = { version = "0.24.0", path = "./vortex-layout" }
vortex-mask = { version = "0.24.0", path = "./vortex-mask" }
vortex-proto = { version = "0.24.0", path = "./vortex-proto" }
vortex-runend = { version = "0.24.0", path = "./encodings/runend" }
vortex-sampling-compressor = { version = "0.24.0", path = "./vortex-sampling-compressor" }
vortex-scalar = { version = "0.24.0", path = "./vortex-scalar", default-features = false }
vortex-scan = { version = "0.24.0", path = "./vortex-scan", default-features = false }
vortex-sparse = { version = "0.24.0", path = "./encodings/sparse" }
vortex-zigzag = { version = "0.24.0", path = "./encodings/zigzag" }
# END crates published by this project

worker = "0.5.0"
xshell = "0.2.6"
zigzag = "0.1.0"

[workspace.lints.rust]
macro_use_extern_crate = "deny"
redundant_lifetimes = "deny"
unsafe_op_in_unsafe_fn = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
as_ptr_cast_mut = "deny"
borrow_as_ptr = "deny"
cargo = { level = "deny", priority = -1 }
cast_possible_truncation = "deny"
collection_is_never_read = "deny"
cognitive_complexity = "deny"
debug_assert_with_mut_call = "deny"
derive_partial_eq_without_eq = "deny"
exit = "deny"
expect_fun_call = "deny"
expect_used = "deny"
equatable_if_let = "deny"
fallible_impl_from = "deny"
get_unwrap = "deny"
host_endian_bytes = "deny"
if_then_some_else_none = "deny"
inconsistent_struct_constructor = "deny"
manual_assert = "deny"
manual_is_variant_and = "deny"
many_single_char_names = "deny"
mem_forget = "deny"
multiple_crate_versions = "allow"
or_fun_call = "deny"
panic = "deny"
# panic_in_result_fn = "deny" -- we cannot disable this for tests to use assertions
redundant_clone = "deny"
same_name_method = "deny"
tests_outside_test_module = "deny"
# todo = "deny"
# unimplemented = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"
use_debug = "deny"

[profile.release]
codegen-units = 1
lto = "thin"      # attempts to perform optimizations across all crates within the dependency graph

[profile.bench]
codegen-units = 16
debug = "full"
lto = false

[profile.bench_assert]
inherits = "bench"
debug-assertions = true
