allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
single-char-binding-names-threshold = 2
disallowed-types = ["std::collections::HashMap", "std::collections::HashSet"]
