[package]
name = "vortex-tui"
authors = { workspace = true }
categories = { workspace = true }
description = "a small but might tool for working with Vortex files"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
crossterm = { workspace = true }
futures-util = { workspace = true }
humansize = { workspace = true }
indicatif = { workspace = true, features = ["futures"] }
parquet = { workspace = true, features = ["arrow", "async"] }
ratatui = { workspace = true }
taffy = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
vortex = { workspace = true, features = ["tokio", "parquet"] }
vortex-layout = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "vx"
path = "src/main.rs"
