[package]
name = "vortex"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex file format with all builtin codecs and a sampling compressor."
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
vortex-alp = { workspace = true }
vortex-array = { workspace = true }
vortex-btrblocks = { workspace = true }
vortex-buffer = { workspace = true }
vortex-bytebool = { workspace = true }
vortex-datetime-parts = { workspace = true }
vortex-dict = { workspace = true }
vortex-dtype = { workspace = true, default-features = true }
vortex-error = { workspace = true }
vortex-expr = { workspace = true }
vortex-fastlanes = { workspace = true }
vortex-file = { workspace = true, optional = true, default-features = true }
vortex-flatbuffers = { workspace = true }
vortex-fsst = { workspace = true }
vortex-io = { workspace = true, optional = true }
vortex-ipc = { workspace = true }
vortex-layout = { workspace = true }
vortex-mask = { workspace = true }
vortex-proto = { workspace = true, default-features = true }
vortex-runend = { workspace = true }
vortex-scalar = { workspace = true }
vortex-sparse = { workspace = true }
vortex-zigzag = { workspace = true }

[features]
default = ["files"]
files = ["dep:vortex-file", "dep:vortex-io"]
object_store = ["vortex-file/object_store"]
parquet = ["vortex-error/parquet"]
python = ["vortex-error/python"]
tokio = ["vortex-io/tokio", "vortex-file/tokio"]
proto = ["vortex-expr/proto", "vortex-error/prost"]
