[package]
name = "vortex-zigzag"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex zig zag array"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-mask = { workspace = true }
vortex-scalar = { workspace = true }
zigzag = { workspace = true }

[dev-dependencies]
vortex-array = { workspace = true, features = ["test-harness"] }

[lints]
workspace = true
