[package]
name = "vortex-scalar"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex Scalars"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
arbitrary = { workspace = true, optional = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
datafusion-common = { workspace = true, optional = true }
flatbuffers = { workspace = true, optional = true }
flexbuffers = { workspace = true, optional = true }
getrandom_v02 = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
paste = { workspace = true }
serde = { workspace = true, optional = true, features = ["rc"] }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true, features = ["arrow"] }
vortex-error = { workspace = true }
vortex-flatbuffers = { workspace = true, optional = true }
vortex-proto = { workspace = true, optional = true }

[dev-dependencies]
flexbuffers = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true

[features]
# Uncomment for improved IntelliJ support
#default = ["flatbuffers", "proto", "serde"]
arbitrary = ["dep:arbitrary"]
datafusion = ["dep:datafusion-common"]
flatbuffers = [
    "dep:flatbuffers",
    "dep:flexbuffers",
    "dep:serde",
    "vortex-flatbuffers/scalar",
    "vortex-error/flatbuffers",
    "vortex-error/flexbuffers",
]
proto = ["vortex-proto/scalar"]
serde = ["dep:serde", "serde/derive", "vortex-dtype/serde"]
