[package]
name = "vortex-scalar"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex Scalars"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
arbitrary = { workspace = true, optional = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
bytes = { workspace = true }
datafusion-common = { workspace = true, optional = true }
getrandom_v02 = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
paste = { workspace = true }
prost = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true, features = ["arrow"] }
vortex-error = { workspace = true }
vortex-proto = { workspace = true, features = ["scalar"] }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true

[features]
arbitrary = ["dep:arbitrary"]
datafusion = ["dep:datafusion-common"]
