[package]
name = "vortex-error"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex errors"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
datafusion = ["datafusion-common"]
flatbuffers = ["dep:flatbuffers"]
python = ["dep:pyo3"]

[dependencies]
arrow-schema = { workspace = true }
datafusion-common = { workspace = true, optional = true }
flatbuffers = { workspace = true, optional = true }
flexbuffers = { workspace = true, optional = true }
jiff = { workspace = true }
object_store = { workspace = true, optional = true }
parquet = { workspace = true, optional = true }
pyo3 = { workspace = true, optional = true }
rancor = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"], optional = true }
url = { workspace = true }
worker = { workspace = true, optional = true }

[lints]
workspace = true
