[package]
name = "vortex-mask"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex Mask - sorted, unique, non-negative integers"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
arrow-buffer = { workspace = true }
itertools = { workspace = true }
vortex-error = { workspace = true }

[lints]
workspace = true
