[package]
name = "vortex-dict"
version = { workspace = true }
description = "Vortex dictionary array"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
categories = { workspace = true }
readme = { workspace = true }

[features]
test-harness = ["rand", "vortex-fsst"]

[dependencies]
arrow-buffer = { workspace = true }
num-traits = { workspace = true }
# test-harness
rand = { workspace = true, optional = true }
rustc-hash = { workspace = true }
rkyv = { workspace = true }
serde = { workspace = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-fsst = { workspace = true, optional = true }
vortex-mask = { workspace = true }
vortex-scalar = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
divan = { workspace = true }
rand = { workspace = true }
vortex-array = { workspace = true, features = ["test-harness"] }

[[bench]]
name = "dict_compress"
harness = false
required-features = ["test-harness"]

[[bench]]
name = "dict_compare"
harness = false
required-features = ["test-harness"]

[[bench]]
name = "dict_mask"
harness = false

[[bench]]
name = "chunked_dict_array_builder"
harness = false
required-features = ["test-harness"]
