[package]
name = "vortex-layout"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex layouts provide a way to perform lazy push-down scans over abstract storage"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
async-trait = { workspace = true }
bit-vec = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
flatbuffers = { workspace = true }
flume = { workspace = true }
futures = { workspace = true, features = ["alloc", "executor"] }
getrandom_v03 = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
roaring = { workspace = true, optional = true }
sketches-ddsketch = { workspace = true }
tokio = { workspace = true, features = ["rt"], optional = true }
tracing = { workspace = true, optional = true }
tracing-futures = { workspace = true, features = [
    "futures-03",
], optional = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-expr = { workspace = true }
vortex-flatbuffers = { workspace = true, features = ["layout"] }
vortex-mask = { workspace = true }
vortex-metrics = { workspace = true }

[dev-dependencies]
futures = { workspace = true, features = ["executor"] }
rstest = { workspace = true }

[features]
roaring = ["dep:roaring"]
tokio = ["dep:tokio", "vortex-error/tokio"]
tracing = ["dep:tracing", "dep:tracing-futures"]

[lints]
workspace = true
