[package]
name = "vortex-runend"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex run end encoded array"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
arrow-buffer = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-mask = { workspace = true }
vortex-scalar = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
divan = { workspace = true }
rand = { workspace = true }
vortex-array = { workspace = true, features = ["test-harness"] }

[[bench]]
name = "run_end_filter"
harness = false

[[bench]]
name = "run_end_null_count"
harness = false

[[bench]]
name = "run_end_compress"
harness = false
