name: PR Benchmarks

env:
  DUCKDB_VERSION: v1.2.2

on:
  pull_request:
    types: [ labeled, synchronize ]
    branches: [ "develop" ]
  workflow_dispatch: { }

permissions:
  actions: write
  contents: read
  pull-requests: write
  id-token: write

jobs:
  label_trigger:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[benchmark]') || github.event.label.name == 'benchmark' && github.event_name == 'pull_request' }}
    steps:
      # We remove the benchmark label first so that the workflow can be re-triggered.
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: benchmark

  build-duckdb:
    needs: label_trigger
    runs-on:
      - runs-on=${{ github.run_id }}
      - family=c6id.8xlarge
      - image=ubuntu24-full-x64
      - spot=false
      - tag=${{ matrix.id }}
    steps:
      - uses: runs-on/action@v1
      - name: Cache duckdb compiled binary
        uses: runs-on/cache@v4
        id: cache-duckdb-binary
        with:
          key: "${{ runner.os }}-duckdb-linux_amd64-${{ env.DUCKDB_VERSION }}"
          path: ${{ github.workspace }}/duckdb/build/release/duckdb

      - name: Install duckdb compile requirements
        if: steps.cache-duckdb-binary.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install ninja-build cmake build-essential make ccache clang -y

      - name: Build duckdb binary
        if: steps.cache-duckdb-binary.outputs.cache-hit != 'true'
        env:
          CC: clang
          CXX: clang++
          GEN: ninja
          NATIVE_ARCH: 1
          DUCKDB_PLATFORM: linux_amd64
          LTO: thin
        run: |
          git clone https://github.com/duckdb/duckdb
          cd duckdb
          git checkout "$DUCKDB_VERSION"
          make release

  bench:
    needs: build-duckdb
    runs-on:
      - runs-on=${{ github.run_id }}
      - family=c6id.8xlarge
      - image=ubuntu24-full-x64
      - spot=false
      - tag=${{ matrix.benchmark.id }}
    strategy:
      matrix:
        benchmark:
          - id: random_access
            name: Random Access
          - id: compress
            name: Compression
    if: ${{ contains(github.event.head_commit.message, '[benchmark]') || github.event.label.name == 'benchmark' && github.event_name == 'pull_request' }}
    steps:
      - uses: runs-on/action@v1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: "recursive"
      # rustup is pre-installed on the ubuntu24-full-x64 image.

      - name: Cache duckdb compiled binary
        uses: runs-on/cache@v4
        id: cache-duckdb-binary
        with:
          # This should always be true so fail here, then we can figure out why the cache was empty.
          fail-on-cache-miss: true
          key: "${{ runner.os }}-duckdb-linux_amd64-${{ env.DUCKDB_VERSION }}"
          path: ${{ github.workspace }}/duckdb/build/release/duckdb

      - name: Add duckdb to path
        run: |
          echo "${{ github.workspace }}/duckdb/build/release/" >> $GITHUB_PATH

      - name: Build binary
        shell: bash
        env:
          RUSTFLAGS: '-C target-cpu=native -C force-frame-pointers=yes'
        run: |
          cargo build --bin ${{ matrix.benchmark.id }} --package bench-vortex --profile release_debug

      - name: Setup Polar Signals
        uses: polarsignals/gh-actions-ps-profiling@v0.4.0
        with:
          polarsignals_cloud_token: ${{ secrets.POLAR_SIGNALS_API_KEY }}
          labels: 'branch=${{ github.ref_name }};gh_run_id=${{ github.run_id }};benchmark=${{ matrix.benchmark.id }}'
          profiling_frequency: 200

      - name: Run ${{ matrix.benchmark.name }} benchmark
        shell: bash
        run: |
          target/release_debug/${{ matrix.benchmark.id }} -d gh-json --skip-rebuild | tee ${{ matrix.benchmark.id }}.json

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::375504701696:role/GitHubBenchmarkRole
          aws-region: us-east-1

      - name: Install uv
        uses: spiraldb/actions/.github/actions/setup-uv@0.11.0
        with:
          sync: false

      - name: Compare results
        shell: bash
        run: |
          set -Eeu -o pipefail -x

          base_commit_sha=${{ github.event.pull_request.base.sha }}

          aws s3 cp s3://vortex-benchmark-results-database/data.json.gz - \
            | gzip -d \
            | grep $base_commit_sha \
            > base.json

          echo '# Benchmarks: ${{ matrix.benchmark.id }}' > comment.md
          echo '<details>' >> comment.md
          echo '<summary>Table of Results</summary>' >> comment.md
          echo '' >> comment.md
          uv run --no-project scripts/compare-benchmark-jsons.py base.json ${{ matrix.benchmark.id }}.json \
            >> comment.md
          echo '</details>' >> comment.md

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: comment.md
          comment-tag: bench-pr-comment-${{ matrix.benchmark.id }}

  sql:
    needs: label_trigger
    uses: ./.github/workflows/sql-benchmarks.yml
    secrets: inherit
    with:
      mode: 'pr'
