name: Python & Rust docs

on:
  push:
    branches: [ develop ]
  workflow_dispatch: { }

permissions:
  actions: read
  deployments: write
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cleanup
      - uses: ./.github/actions/setup-rust
      - uses: spiraldb/actions/.github/actions/setup-uv@0.2.0

      - name: build Python and Rust docs
        run: |
          uv run make -C docs html
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: docs

      # Note, since we use an API token we run it in a separate job that doesn't run any repository code.
      - name: Upload artifacts to CloudFlare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy docs --project-name=vortex-docs
