name: Vortex Docs

on:
  push:
    branches: [ develop ]
  workflow_dispatch: { }

permissions:
  actions: read
  deployments: write
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: ./.github/actions/cleanup
      - uses: ./.github/actions/setup-rust
      - uses: spiraldb/actions/.github/actions/setup-uv@0.7.0

      - name: build Python and Rust docs
        run: |
          uv run make -C docs html
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Note, since we provide the job with a CloudFlare scoped API token, we run it in a separate job that doesn't
      # execute any repository code.
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Extract Pages Artifact
        run: mkdir docs && tar -xvf artifact.tar -C docs
        shell: bash
      - name: Upload artifacts to CloudFlare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/ --project-name=vortex-docs --branch=${{ github.head_ref || github.ref_name }}
