name: Java

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

on:
  push:
    branches: [ "develop" ]
    tags: [ "*" ]
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read

jobs:
  build-macos:
    name: Build on macOS Apple Silicon
    runs-on: macos-15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: ./.github/actions/cleanup
      - uses: rui314/setup-mold@v1
      - uses: ./.github/actions/setup-rust
      - run: cargo build --release --package vortex-jni
      - uses: actions/upload-artifact@v4
        with:
          name: libvortex_jni_darwin_aarch64.zip
          path: target/release/libvortex_jni.dylib
          retention-days: 1
          if-no-files-found: error
  build-linux-amd:
    name: Build on Linux x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: ./.github/actions/cleanup
      - uses: rui314/setup-mold@v1
      - uses: ./.github/actions/setup-rust
      - run: cargo build --release --package vortex-jni
      - uses: actions/upload-artifact@v4
        with:
          name: libvortex_jni_linux_amd64.zip
          path: target/release/libvortex_jni.so
          retention-days: 1
          if-no-files-found: error
  build-linux-aarch64:
    name: Build on Linux AArch64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: ./.github/actions/cleanup
      - uses: rui314/setup-mold@v1
      - uses: ./.github/actions/setup-rust
      - run: cargo build --release --package vortex-jni
      - uses: actions/upload-artifact@v4
        with:
          name: libvortex_jni_linux_aarch64.zip
          path: target/release/libvortex_jni.so
          retention-days: 1
          if-no-files-found: error
  package-java:
    name: Package Java artifact
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux-amd, build-linux-aarch64]
    defaults:
      run:
        working-directory: ./java
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: ./.github/actions/cleanup
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Copy native JNI libs
        run: |
          mkdir -p vortex-jni/src/main/resources/native/darwin-aarch64
          mkdir -p vortex-jni/src/main/resources/native/linux-aarch64
          mkdir -p vortex-jni/src/main/resources/native/linux-amd64
          cp ../libvortex_jni_darwin_aarch64.zip/libvortex_jni.dylib ./vortex-jni/src/main/resources/native/darwin-aarch64
          cp ../libvortex_jni_linux_aarch64.zip/libvortex_jni.so ./vortex-jni/src/main/resources/native/linux-aarch64
          cp ../libvortex_jni_linux_amd64.zip/libvortex_jni.so ./vortex-jni/src/main/resources/native/linux-amd64
      - name: Build Java
        run: ./gradlew shadowJar
      - name: Publish to Maven Central
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
